#Author: 

TOP=../..
include $(TOP)/configure/CONFIG

#add macros here

#optimization of db files using dbst(DEFAULT:NO)
#DB_OPT=YES

DB+=NDPluginThreshold.template


include $(TOP)/configure/RULES

#add rules here
